### ISSUE TITLE
WotLK Classic Update <3

### ISSUE THREAD

**Issue by MurderOnMyMind7** [noyanbaykal/UIChanges#1]
Hey, sorry to bother you, but I was HUGE fan of Party Pet Frames, and I would love it if you would be so kind as to update your addon to function properly with WotLK Classic. I'm sure you're busy, but when you get a chance it would mean a lot to me. I really enjoy your work! Thanks a bunch! Have a great day <3

**Comment by noyanbaykal** [comment]
Hey MurderOnMyMind7, thank you very much for your message! I just got around to testing the addon with the WOTLK client and pushed the changes for the new version. I also uploaded the updated zip on CurseForge and WoWInterface, it will be available on those platforms once it is approved. I really appreciate your messages, hope you will continue enjoying the addon in WOTLK!
